apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  namespace: app-prod
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true